#!/bin/bash

# Récupérer les valeurs des variables d'environnement WATER et STIR
WATER="$WATER"
STIR="$STIR"

# Convertir de base water à base 10
water_decimal=$(echo "$WATER" | tr -d 'a-z' | tr -d '.' | rev | awk '{s=0} {for (i=1; i<=length; i++) s+=ord(substr($0, i, 1))-96} END {print s}')

# Convertir de base stir à base 10
stir_decimal=$(echo "$STIR" | tr -d 'a-z' | tr -d '.' | rev | awk '{s=0} {for (i=1; i<=length; i++) s+=ord(substr($0, i, 1))-96} END {print s}')

# Additionner les valeurs en base 10
result_decimal=$((water_decimal + stir_decimal))

# Convertir de base 10 à base bestchol
result_bestchol=""
while [ "$result_decimal" -gt 0 ]; do
    remainder=$((result_decimal % 11))
    if [ "$remainder" -eq 10 ]; then
        result_bestchol="a$result_bestchol"
    else
        result_bestchol="$remainder$result_bestchol"
    fi
    result_decimal=$((result_decimal / 11))
done

# Afficher le résultat
echo "$result_bestchol"

